# Generated by Django 2.0.7 on 2018-07-18 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videorequest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='date_addedd',
            new_name='date_added',
        ),
    ]
